name: Docker Image CI

#on: [pull_request, push] 
on: 
  push:
    branches: [ "feature/customization-of-the-stream-name-1.16.2" ]
  pull_request:
    branches: [ "feature/customization-of-the-stream-name-1.16.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ## Sets environment variable for package cloud
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }} 
      #PACKAGECLOUD_URL:
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gst-rtspclientsink:$(date +%s)
