name: Docker Image CI

#on: [pull_request, push] 
on: 
  push:
    branches: [ "feature/customization-of-the-stream-name-1.16.2" ]
  pull_request:
    branches: [ "feature/customization-of-the-stream-name-1.16.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Build the Docker image for cross-compiling the gst module
        run: docker build . --file Dockerfile --secrets --build-arg "PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }}" --tag gst-1.0-rtspclientsink-1.16.2:$(date +%s)

